apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tyje2imfv-go
  janus-idp.io/tekton: tyje2imfv-go
  backstage.io/kubernetes-id: tyje2imfv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyje2imfv-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
