apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tyje2imfv-go-gitops
  description: This is GitOps manifest for tyje2imfv-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tyje2imfv-go
    backstage.io/kubernetes-id: tyje2imfv-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tyje2imfv-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tyje2imfv-go
